version: '3.9'
services:
    db:
        image: postgres:13.3
        container_name: trello_data_test
        hostname: db_trello
        restart: unless-stopped
        environment:
            POSTGRES_DB: 'db_trello'
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'admin'
            PGDATA: '/var/lib/postgresql/data/pgdata'
        volumes:
            - trello_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - postgres
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'pgadmin@mail.com'
            PGADMIN_DEFAULT_PASSWORD: 'admin'
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - '5050:80'
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge
volumes:
    trello_data:
    pgadmin:
